<?php

namespace Acme\LibraryBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;
use Doctrine\ORM\Query\ResultSetMappingBuilder;

/**
 * AuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorRepository extends EntityRepository
{
    public function getFindAllQuery()
    {
        $rsm = new ResultSetMappingBuilder($this->getEntityManager());
        $rsm->addRootEntityFromClassMetadata('Acme\LibraryBundle\Entity\Author', 'a');

        $query = $this->getEntityManager()->createNativeQuery('select * from Author a', $rsm);

        return $query;
    }
}
